// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABixTUEI0fDgAhRKixXWWYARTMOKOU6Ao',
    appId: '1:511263269898:web:05ea1581f15c77c2f66bf3',
    messagingSenderId: '511263269898',
    projectId: 'flutter-djila',
    authDomain: 'flutter-djila.firebaseapp.com',
    storageBucket: 'flutter-djila.appspot.com',
    measurementId: 'G-TK45CMPS90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPQ_4F61nJ6SryfhC5cPopH_65VvuUVGc',
    appId: '1:511263269898:android:5b41ecb73d49e90af66bf3',
    messagingSenderId: '511263269898',
    projectId: 'flutter-djila',
    storageBucket: 'flutter-djila.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDndysT2anNPJGW_2g6sTkGzjzHtE39A_Q',
    appId: '1:511263269898:ios:d4944f63cbe89714f66bf3',
    messagingSenderId: '511263269898',
    projectId: 'flutter-djila',
    storageBucket: 'flutter-djila.appspot.com',
    iosBundleId: 'com.djila.app',
  );
}
